kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmeParticipantModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeParticipantModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/util/messages/RoomParticipantsMessageBuilder.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/KmeMessageParser.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/KmeMessageEvent.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeParticipantsModuleMessage.kt
KMEMA-305. Participants: Removed participants stay in the room.
=> KMEMA-83. [Moderator] - Remove participants from room.

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/whiteboard/KmeWhiteboardContentViewModel.kt
=> KMEMA-304 WhiteBoard: Mobile app doesn't switch to a new added Board

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeDefaultPlayerEventHandler.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentFragment.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaView.kt
KMEMA-348 uTest Cycle - View Shared Youtube Video: Video stopped and no more resumed (for student) while switching app
KMEMA-349 uTest Cycle - YouTube functionality: Video stopped and no more resumed while "picture in picture" mode enabled
KMEMA-350 uTest Cycle - View Shared YouTube Video: Video stopped and no more resumed while rotating device
=> KMEMA-348, 349, 350

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentFragment.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentViewModel.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/di/ContentShareViewModels.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/webrtc/audio/IKmeAudioManager.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/webrtc/audio/KmeAudioManagerImpl.kt
https://kaltura.atlassian.net/browse/KMEMA-347
=> [kmema-347] fixed audio volume problem when video was appeared 

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/slides/KmeSlidesView.kt
https://kaltura.atlassian.net/browse/KMEMA-429
=> [kmema-429]

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmeNoteModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeNoteModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/response/room/notes/KmeGetRoomNoteResponse.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/service/KmeRoomNotesApiService.kt
https://kaltura.atlassian.net/browse/KMEMA-442
=> [Kmema-442] added single note data service

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentFragment.kt
=> [kmema-483] fixed video sound problem when application is in background

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/poll/KmeDefaultPollEventHandler.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/poll/KmeQuickPollView.kt
=> [kmema-485] fixed pull view show problem when user changes network (wifi to 3g)

kmeapp/src/main/java/com/kme/kaltura/kmeapplication/KmeApplication.kt, kmeapp/src/main/java/com/kme/kaltura/kmeapplication/view/activity/SplashActivity.kt, kmeapp/src/main/java/com/kme/kaltura/kmeapplication/view/fragment/RoomNoteFragment.kt, kmeapp/src/main/java/com/kme/kaltura/kmeapplication/viewmodel/PeerConnectionViewModel.kt, kmeapp/src/main/java/com/kme/kaltura/kmeapplication/viewmodel/RoomNoteViewModel.kt
=> [kmema-489] resolved kme sdk app build problem

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/slides/KmeSlidesContentFragment.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/whiteboard/KmeWhiteboardContentViewModel.kt
=> [kmema-494] Refactor SDK KmeWhiteboardContentViewModel  ConsumableValue with LiveData

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeTermsModuleImpl.kt
changed terms anotation message
=> terms module anotation  missed

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeBreakoutModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeRoomControllerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeRoomModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeWebSocketModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ui/widget/overlap/KmeOverlapLayout.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/KmeWebSocketHandler.kt
KMEMA-514 I as a participant in a BOR want to call a moderator
https://kaltura.atlassian.net/browse/KMEMA-514
=> KMEMA-514 I as a participant in a BOR want to call a moderator

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeRoomControllerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeBreakoutModuleMessage.kt
KMEMA-513 I as a participant want to be directed to a BOR with the new permissions
https://kaltura.atlassian.net/browse/KMEMA-513
KMEMA-520 I as a moderator want to see if I was called from a certain room and address it
https://kaltura.atlassian.net/browse/KMEMA-520
=> KMEMA-513, 520

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaView.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmeBreakoutModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeBreakoutModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeRoomControllerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeBreakoutModuleMessage.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/participant/KmeParticipant.kt
KMEMA-515 I as a participant in a BOR want to see a message/ file/ media broadcasted from a moderator 
https://kaltura.atlassian.net/browse/KMEMA-515
=> KMEMA-515 

kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/response/room/settings/KmeDefaultSettings.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/type/permissions/KmeAudioNotificationValue.kt
=> [kmema-506] added new permission type

kmesdk/src/main/java/com/kme/kaltura/kmesdk/Extensions.kt
=> [KMEMA-601] App crash when playing gif and animated gif files

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/poll/KmeQuickPollView.kt
KMEMA-639 Quick Polls - Start a quick poll with faces and then start another quick poll with A,B,C,D
https://kaltura.atlassian.net/browse/KMEMA-639
=> KMEMA-639 

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmeNoteDownloadModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeNoteModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/KmeFileLoader.kt
=> [kmema-630] Notes downloaded to a phone can't be found on the phone

kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/KmeMessageModule.kt
=> [KMEMA-684] the echo cancellation should apply only when the video is running

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/desktop/KmeDesktopShareViewModel.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/IKmeUserController.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/impl/KmeUserControllerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmeSettingsModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeRoomControllerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeSettingsModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/response/user/KmeUserSetting.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/KmeMessageParser.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/KmeMessageEvent.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeParticipantSettingsModuleMessage.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeRoomSettingsModuleMessage.kt
kmema-565
Version of 1.5.0 backlog
=> [kmema-565] Removed individual permissions do not affect mob app users

kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeDefaultPlayerEventHandler.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentFragment.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentViewModel.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/IKmePeerConnectionModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmePeerConnectionModuleImpl.kt
KMEMA-689
Version of 1.5.0 backlog
=> [KMEMA-689] When video finished playing on stage and user rejoins room, mic remains visually hard-muted

kmesdk/build.gradle, kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/room/impl/KmeWebSocketModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/di/KmeKoinExtensions.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/di/LoggerModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/di/WebSocketModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/logger/IKmeLogger.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/logger/KmeLoggerImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/KmeWebSocketHandler.kt
=> [KMEMA-696] [Security Audit] - Information leakage from android console

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/IKmeRoomController.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/IKmeRecordingModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmeRecordingModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmeRoomModuleImpl.kt
=> [kmema-729] Refactoring recording module, move all logic from app inside sdk 

kmesdk/src/main/java/com/kme/kaltura/kmesdk/controller/impl/KmeRoomControllerImpl.kt
[KMEMA-722] (https://kaltura.atlassian.net/browse/KMEMA-722)
Breakout - Crash when launching the breakout room
[KMEMA-724] (https://kaltura.atlassian.net/browse/KMEMA-724) Breakout - Crash after ending the Breakout room
[KMEMA-722]: https://kaltura.atlassian.net/browse/KMEMA-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KMEMA-724]: https://kaltura.atlassian.net/browse/KMEMA-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KMEMA-722, 724

kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmeSettingsModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/rest/response/user/KmeUserSetting.kt, kmesdk/src/main/res/layout/fragment_media_content.xml
=> [SUP-30917] participant is still able to do Room Chat, Q&A, 1:1 Chat

kmesdk/build.gradle, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentFragment.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaContentViewModel.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/content/playkit/KmeMediaView.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmeParticipantModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmePeerConnectionModuleImpl.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/util/messages/PlayerStateMessageBuilder.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/KmeMessageEvent.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/KmeMessageModule.kt, kmesdk/src/main/java/com/kme/kaltura/kmesdk/ws/message/module/KmeVideoModuleMessage.kt
[KMEMA-685] (https://kaltura.atlassian.net/browse/KMEMA-685)
uTest - YouTube player stops in the Android native app and does not resume after rejoining room
[KMEMA-694] (https://kaltura.atlassian.net/browse/KMEMA-694) User can't hear audio played on stage upon joining the session
[KMEMA-685]: https://kaltura.atlassian.net/browse/KMEMA-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KMEMA-694]: https://kaltura.atlassian.net/browse/KMEMA-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kmema 685, 694

kmesdk/src/main/res/layout/layout_poll_results.xml
=> [KMEMA-755] Quick Polls - Results page for the poll is not displayed properly in landscape mode

kmesdk/src/main/java/com/kme/kaltura/kmesdk/module/impl/KmeSettingsModuleImpl.kt
=> [kmema-739] Guest Participants: Removed individual permissions affect all mobile users
